# Site Settings
title: My Resume
url: 'https://mdaviesnz.github.io/online-resume/'
baseurl: '/online-resume' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Michael Davies
tagline: System, Network, Infrastructure Engineer
pic: profile2.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'A career built within OceanaGold from an entry level position through to a senior leadership role. A team member, respected for many years of experience and willingness to share information and assist others. Always keenly involved in innovation and growth, both personally and professionally. Continually seeking new knowledge, skills and abilities.'

#sidebar links
email: michael@davies.net.nz
phone: 027 416 8023
#website: michael.davies.net.nz #do not add http://
#linkedin: alandoe
#github: sharu725
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
